config/routes.rb
Blog::Application.routes.draw do
  get "posts/tab"
  
  resources :posts do 
    resources :comments
 
  end
  match "/auth/facebook/callback" => "sessions#callback"
  match "/logout" => "sessions#destroy", :as => :logout
  resources :posts do 
    resources :comments
    
  end

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body, :commenter

  validates :commenter, :presence => true
  validates :body, :presence => true,
   					 :length => { :minimum => 5}
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title

  has_many  :comments
  validates :title, :presence => true
  validates :content, :presence => true,
   					 :length => { :minimum => 5}

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create!do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      if user.provider == "facebook"
         user.name = auth["info"]["name"]
      else
         user.name = auth["info"]["nickname"]
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

#I don't know what will happen.

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
	 @post = Post.find(params[:post_id])
 	 @comment = Post.find(params[:post_id]).comments.new(params[:comment])
 	 if @comment.save
  		redirect_to post_path(@post)
	 else 
 		render :template => "posts/show"
	 end
	end 
    def destroy
    	@comment = Comment.find(params[:id])
    	@comment.destroy
    	render json:{ comment: @comment }
    end
end

app/controllers/posts_controller.rb
	#coding : utf-8

class PostsController < ApplicationController
 def index
  @posts = Post.all( :order => "created_at DESC")
 end
 def show
 	@post = Post.find(params[:id])
 	@comment = Post.find(params[:id]).comments.build
 end
 def new
   @post = Post.new 
 end
 def create
 	@post = Post.new(params[:post])
 	if @post.save
 		 redirect_to posts_path , notice: '作成されました！'
 	else
 		render action: 'new'
 	end
 end
 def edit
 	@post = Post.find(params[:id])
 end

 def update
 	@post = Post.find(params[:id])
 	if @post.update_attributes(params[:post])
 		redirect_to posts_path, notice: '更新されました！'
 	else
 		render action: 'edit'
 	end
 end
 def destroy
    @post = Post.find(params[:id])
    @post.destroy
    render json: {post: @post}
 end 
 def tab
 	@posts = Post.all( :order => "updated_at DESC")
 end
 
 
end

app/controllers/sessions_controller.rb
#coding: utf-8
class SessionsController < ApplicationController
  def callback
    #omniauth.auth環境変数を取得
    auth = request.env["omniauth.auth"]
    #Userモデルを検索
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"])

    if user
       # 既存のユーザ情報があった場合　ルートに遷移させます
       session[:user_id] = user.id
       redirect_to root_url, :notice => "ログインしました。"
    else
       # Userモデルに:providerと:uidが無い場合（外部認証していない）、保存してからルートへ遷移させる
       User.create_with_omniauth(auth)
       redirect_to root_url, :notice =>  "#{auth["info"]["name"]}さんの#{auth["provider"]}アカウントと接続しました。"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Log out"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:#eee">
　 <div id="user_nav">
    <% if current_user %>
       <%= current_user.name %>さん <%= link_to "ログアウト" ,logout_path %>
    <% else %>
       <%= link_to "facebookでlogin", "/auth/facebook" %>
    <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

<% if @post.errors.any? %>
<ul>
<% @post.errors.full_messages.each do |msg|%>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<div class="field">
 <%= f.label :title %>
 <%= f.text_field :title %>
</div>

<div class="field">
 <%= f.label :content %>
 <%= f.text_area :content, :rows => 5 %>
</div>



<div class="actions">
 <%= f.submit %>
</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'home', posts_path %>

app/views/posts/expire.html.erb
<h1>Posts</h1>

<div id="notice"><%= notice %></div>

<%= link_to image_tag('images.jpeg', :size => '200x150'), '/'%>
<ul>
<% @posts.each do |post|%>
<li id="post_<%= post.id %>">
<%= link_to post.title, post_path(post)%> (<%= post.comments.size %>)
<%= link_to 'Edit', edit_post_path(post)%>
<%= link_to 'Delete', post, :confirm => 'Sure?',
                            :method => :delete,
                            :remote => true %>
</li>
<% end %>
</ul>
<%= link_to 'home' , posts_path %> | <%= link_to 'new' , new_post_path %>
|<%= link_to '更新順' , 'posts/tab' %> |<%= link_to '作成順' , posts_path %> |

<script>
$(function(){
 setTimeout(function(){
$('#notice').fadeOut("slow");
},800);
 $('a[data-method="delete"]').on('ajax:success', function(e, data, status, xhr) {
 	$('#post_'+data.post.id).fadeOut("slow");
 });
});

</script>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div id="notice"><%= notice %></div>

<%= link_to image_tag('images.jpeg', :size => '200x150'), '/'%>
<ul>
<% @posts.each do |post|%>
<li id="post_<%= post.id %>">
<%= link_to post.title, post_path(post)%> (<%= post.comments.size %>)
<%= link_to 'Edit', edit_post_path(post)%>
<%= link_to 'Delete', post, :confirm => 'Sure?',
                            :method => :delete,
                            :remote => true %>
</li>
<% end %>
</ul>

<%= link_to 'home' , posts_path %> | <%= link_to 'new' , new_post_path %>
|<%= link_to '更新順' , 'posts/tab' %> |<%= link_to '作成順' , posts_path %> |
<script>
$(function(){
 setTimeout(function(){
$('#notice').fadeOut("slow");
},800);
 $('a[data-method="delete"]').on('ajax:success', function(e, data, status, xhr) {
 	$('#post_'+data.post.id).fadeOut("slow");
 });
});

</script>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>


<%= link_to 'home', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<h2>Comments</h2>
<ul>
<% if @post.comments.any? %>
<% @post.comments.each do |comment| %>
<li id="comment_<%= comment.id %>">
<%= comment.body %>(by <%= comment.commenter %>)
<%= link_to 'delete', [comment.post, comment], 
:confirm => 'Sure?',
:method => :delete,
:remote => true %>
</li>
<% end %>
<% else %>
<li> no comment yet.</li>
<% end %>
</ul>


<h2>Add a comment</h2>
<%= form_for([@post, @comment]) do |f| %>

<% if @comment.errors.any? %>
<ul>
<% @comment.errors.full_messages.each do |msg| %>
<li><%=msg %></li>
<% end %>
</ul>
<% end %>


<div class="field">
 <%= f.label :commmenter %>
 <%= f.text_field :commenter %>
</div>

<div class="field">
 <%= f.label :body %>
 <%= f.text_area :body, :rows => 5 %>
</div>

<div class="actions">
 <%= f.submit %>
</div>

<% end %>


<%= link_to 'home', posts_path %>

<script>
$(function(){
 $('a[data-method="delete"]').on('ajax:success', function(e, data, status, xhr) {
 	$('#comment_'+data.comment.id).fadeOut("slow");
 });
});

</script>

app/views/posts/tab.html.erb
<h1>Posts</h1>

<div id="notice"><%= notice %></div>

<%= link_to image_tag('images.jpeg', :size => '200x150'), '/'%>
<ul>
<% @posts.each do |post|%>
<li id="post_<%= post.id %>">
<%= link_to post.title, post_path(post)%> (<%= post.comments.size %>)
<%= link_to 'Edit', edit_post_path(post)%>
<%= link_to 'Delete', post, :confirm => 'Sure?',
                            :method => :delete,
                            :remote => true %>
</li>
<% end %>
</ul>
<%= link_to 'home' , posts_path %> | <%= link_to 'new' , new_post_path %>
|<%= link_to '更新順' , 'posts/tab' %> |<%= link_to '作成順' , posts_path %> |

<script>
$(function(){
 setTimeout(function(){
$('#notice').fadeOut("slow");
},800);
 $('a[data-method="delete"]').on('ajax:success', function(e, data, status, xhr) {
 	$('#post_'+data.post.id).fadeOut("slow");
 });
});

</script>